### ISSUE TITLE
requests.get

### ISSUE THREAD

**Issue by Kraash0** [JackhammerYT/RedVidDownloader#3]
In the line 

`self.PostLinks = requests.get("https://jackhammer.pythonanywhere.com//reddit/subreddit/all", params={'subreddit':Subreddit , 'number':NumberOfPosts , 'flair':flair , 'sort':SortBy})`

why have you put this URL link? @JackhammerYT

**Comment by Kraash0** [comment]
@JackhammerYT but how does that url have Reddit data?

**Comment by JackhammerYT** [comment]
@Kraash0 the response server has a praw bot that processes the request and sends back the data. You can learn more about it here: https://www.reddit.com/r/Python/comments/s94nu1/reddownloader_3_released_with_now_the_capability/

**Comment by Kraash0** [comment]
I see. Thanks
