### ISSUE TITLE
quality

### ISSUE THREAD

**Issue by Nolife2018** [JackhammerYT/RedVidDownloader#4]
why is there no 144p, 240p, 480p quality option?

**Comment by JackhammerYT** [comment]
Quality is an ambiguous term actually it basically means the resolution and reddit stores them only in three resolutions 360p , 720p , 1080p on their servers.

**Comment by JackhammerYT** [comment]
I ran a quick check about these resolutions on few video samples and quite few of them did have these so I'll be updating resolution types in next update

**Comment by JackhammerYT** [comment]
Support for following resolutions have been added [here](https://github.com/JackhammerYT/RedVidDownloader/commit/ad9cdc20e06e72788e5f037e1e35e1a2692548d3) and would be released to public in the next stable version release.
